// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIJm0ggeRN46fVQvaHBMSbTgZ0qzlJKQg',
    appId: '1:742415027647:web:2404060af53298d35d250a',
    messagingSenderId: '742415027647',
    projectId: 'hive-5eb83',
    authDomain: 'hive-5eb83.firebaseapp.com',
    storageBucket: 'hive-5eb83.appspot.com',
    measurementId: 'G-RXFHJBD9LX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdweH_cPTdEZkl6bbaJiClBrYyZ9xKQ_U',
    appId: '1:742415027647:android:5470cd3c6414ada35d250a',
    messagingSenderId: '742415027647',
    projectId: 'hive-5eb83',
    storageBucket: 'hive-5eb83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEVG4wxKRfXoQFaNXOon6SngDKXj6-c6U',
    appId: '1:742415027647:ios:ce13a00d0a6c357b5d250a',
    messagingSenderId: '742415027647',
    projectId: 'hive-5eb83',
    storageBucket: 'hive-5eb83.appspot.com',
    iosClientId: '742415027647-n6nkoamh92g466pjp2er2ihpjell24tt.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiveBusiness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEVG4wxKRfXoQFaNXOon6SngDKXj6-c6U',
    appId: '1:742415027647:ios:ce13a00d0a6c357b5d250a',
    messagingSenderId: '742415027647',
    projectId: 'hive-5eb83',
    storageBucket: 'hive-5eb83.appspot.com',
    iosClientId: '742415027647-n6nkoamh92g466pjp2er2ihpjell24tt.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiveBusiness',
  );
}
